### PR TITLE
/auth: Fallback to accounts

### LINKED ISSUE #11: Team might not exist
If team does not exist `/auth` fails completely.

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #11

### CODE REVIEW

File: src/org/zalando/stups/magnificent/api.clj [hunk 1]
```diff
@@ -136,6 +136,19 @@
...
 
+(defn get-team-or-account
+  [team-or-account request]
+  (try+
+    (:body (get-team {:team team-or-account} request))
+    (catch [:http-code 404] []
+      (try+
+        (let [account (:body (get-account {:type "aws" :account team-or-account} request))]
+          (log/warn "Team is actually an account: %s" {:team-or-account team-or-account})
+          account)
```
Comment (harti2006) [inline src/org/zalando/stups/magnificent/api.clj:147]: the account object is different from the team object. Some fields that are used later on might be missing

Comment (prayerslayer) [inline src/org/zalando/stups/magnificent/api.clj:147]: Yes, but in case of `get-auth` we only need the `members` and that field is the same. It's named `get-team-or-account`, so users of this function should be prepared for either, I suppose.

**Comment by harti2006** [comment]
:+1:

**Comment by prayerslayer** [comment]
👍
